export default {
  index: 'Overview',
  installation: 'Installation',
  'github-action': 'GitHub Action',
  configuration: 'Configuration',
  commands: 'Command Reference',
  workflows: 'Workflows',
  'smart-deploy': 'Smart Deploy',
  retrofit: 'Retrofit & PR Comments',
  notifications: 'Notifications',
  dashboard: 'Web Dashboard',
  'ai-providers': 'AI Providers',
  skills: 'Agent Skills',
  plugins: 'Plugins',
  'sf-plugin': 'Salesforce CLI Plugin',
  mcp: 'MCP Server',
  docker: 'Docker',
  'ci-cd': 'CI/CD',
  'ci-authentication': 'CI Authentication'
}
